---
- hosts: localhost
  connection: local
  vars_files:
    - creds.yml
  tasks:
    - name: Save the running configuration
      bigip_config:
        save: yes
        provider: "{{ provider }}"
      tags:
        - save_conf

    - name: Upload absolute image to the BIG-IP
      bigip_software_image:
        image: "{{ filePath }}/{{ image_version }}" #BIGIP-16.0.0-0.0.12.iso
        provider: "{{ provider }}"
        state: present
      delegate_to: localhost
      tags:
        - upload_bigip

    - name: Installs the BIG-IP OS
      bigip_software_install:
        image: "{{ image_version }}" #BIGIP-16.0.0-0.0.12.iso
        volume: "{{ boot_location }}" #HD1.3
        state: installed
        provider: "{{ provider }}"
      delegate_to: localhost
      retries: 3
      delay: 30
      tags:
        - install_bigip

    - name: Verify the system was installed
      bigip_device_info:
        gather_subset:
          - software-volumes
        provider: "{{ provider }}"
      register: bigip_software_install
      tags:
        - verify

    - name: Displays the device info
      debug:
        var: bigip_software_install
      tags:
        - verify

    - name: "Copy the config from {{ current_location }} to {{ boot_location }} cpcfg --source={{ current_location }} --reboot {{ boot_location }}"
      raw: curl -u "{{ provider.user }}":"{{ provider.password }}" -k https://"{{provider.server }}":{{ provider.server_port }}/mgmt/tm/util/bash  -H "Content-type:application/json" -d "{\"command\":\"run\",\"utilCmdArgs\":\"-c 'cpcfg --source={{ current_location }} --reboot {{ boot_location }}'\"}"
      ignore_errors: True
      register: cpcfg
      tags:
        - activate_partition

    - name: Verify the system was installed
      bigip_command:
        commands:
          - show sys software status
        provider: "{{ provider }}"
      register: device_facts
      tags:
        - activate_partition

    - name: Display
      debug:
        var: device_facts
      tags:
        - activate_partition

