---
- hosts: localhost
  connection: local
  vars_files:
    - creds.yml
  tasks:
    - name: Save the running configuration
      bigip_config:
        save: yes
        provider: "{{ provider }}"

    - name: Upload absolute image to the BIG-IP
      bigip_software_image:
        image:  "{{ image_version }}"
        provider: "{{ provider }}"
      tags:
        - upload_bigip

    - name: Installs the BIG-IP OS
      bigip_software_install:
        image: "{{ image_version }}" #BIGIP-16.0.0-0.0.12.iso
        volume: "{{ boot_location }}"
        state: activated
        provider: "{{ provider }}"
      tags:
        - install_bigip
